let list = [
    {
        CREATEDAT: "2024-07-19T03:55:59.447",
        CREATEDBY: "anonymous",
        MODIFIEDAT: "2024-07-19T03:59:52.299",
        MODIFIEDBY: "anonymous",
        EVALCODE: "SL01",
        EMPNO: "38102378",
        NAME: "김재우",
        DEPARTMENTCODE: "33000457",
        DEPARTMENTNAME: "품질기획팀",
        ORGLEVEL2CODE: null,
        ORGLEVEL2NAME: null,
        ORGLEVEL3CODE: null,
        ORGLEVEL3NAME: null,
        ORGLEVEL4CODE: null,
        ORGLEVEL4NAME: null,
        ORGLEVEL5CODE: "33000502",
        ORGLEVEL5NAME: "품질경영실",
        ORGLEVEL6CODE: null,
        ORGLEVEL6NAME: null,
        ORGLEVEL7CODE: "33000457",
        ORGLEVEL7NAME: "품질기획팀",
        JOBGRADECODE: "35010002",
        JOBGRADENAME: "사무직",
        JOBTITLECODE: "C022",
        JOBTITLENAME: "담당",
        ORIGINALSTARTDATE: null,
        HIREDATE: "2021-04-29",
        STATUSBASIC: "재직",
        STATUSCURRENT: "재직",
        JOBCATEGORYCODE: "35010002",
        JOBCATEGORYNAME: "사무직",
        JOBTYPECODE: "35020003",
        JOBTYPENAME: "Production",
        JOBSERIALCODE: "35030010",
        JOBSERIALNAME: "품질",
        JOBCODE: "35170025",
        JOBNAME: "품질",
        JOBPOSITIONCODE: "A003",
        JOBPOSITIONNAME: "-",
        EMPLOYMENTTYPECODE: "D1",
        EMPLOYMENTTYPENAME: "사무직(연봉)",
        TEMPLATEIDS: "619",
        FORMDATAID: "3106",
        GROUPORGCODE: "SL01",
        GROUPORGNAME: "삼립그룹 조직",
        GROUPINSACODE: "SLINSA01",
        GROUPINSANAME: "삼립인사그룹",
        EVAL1ORGCODE: "33000065",
        EVAL1ORGNAME: "CSM팀",
        RATER1EMPNO: "20600010",
        RATER1NAME: "김용건",
        EVAL2ORGCODE: "33000854",
        EVAL2ORGNAME: "연구소",
        RATER2EMPNO: "1960004",
        RATER2NAME: "김진억",
        EVAL3ORGCODE: null,
        EVAL3ORGNAME: null,
        RATER3EMPNO: null,
        RATER3NAME: null,
        EVAL4ORGCODE: null,
        EVAL4ORGNAME: null,
        RATER4EMPNO: null,
        RATER4NAME: null,
        DELETEYN: null,
        SELFSCORE: null,
        EVALSCORE: "75.00",
        UPORGAVG: "68.67",
        UPORGSTDEV: "4.62",
        ORGAVG: "67.75",
        ORGSTDEV: "4.36",
        ADJUSTSCORE: "76.00",
        RANKING: 1,
        EVAL1GRADECODE: "05",
        EVAL1GRADENAME: "U",
        EVAL2SCORE: "76.36",
        EVAL2GRADECODE: "05",
        EVAL2GRADENAME: "U",
        EVAL3SCORE: null,
        EVAL3GRADECODE: null,
        EVAL3GRADENAME: null,
        EVAL4SCORE: null,
        EVAL4GRADECODE: null,
        EVAL4GRADENAME: null,
        FINALSCORE: null,
        FINALGRADECODE: null,
        FINALGRADENAME: null,
        STATUS: "12",
        COMFIRMEVAL: "N",
    },
    {
        CREATEDAT: "2024-07-22T00:49:12.141",
        CREATEDBY: "anonymous",
        MODIFIEDAT: "2024-07-22T04:18:55.547",
        MODIFIEDBY: "anonymous",
        EVALCODE: "FirstHalf2024",
        EMPNO: "38102378",
        NAME: "김재우",
        DEPARTMENTCODE: "33000457",
        DEPARTMENTNAME: "품질기획팀",
        ORGLEVEL2CODE: null,
        ORGLEVEL2NAME: null,
        ORGLEVEL3CODE: null,
        ORGLEVEL3NAME: null,
        ORGLEVEL4CODE: null,
        ORGLEVEL4NAME: null,
        ORGLEVEL5CODE: "33000502",
        ORGLEVEL5NAME: "품질경영실",
        ORGLEVEL6CODE: null,
        ORGLEVEL6NAME: null,
        ORGLEVEL7CODE: "33000457",
        ORGLEVEL7NAME: "품질기획팀",
        JOBGRADECODE: "35010002",
        JOBGRADENAME: "사무직",
        JOBTITLECODE: "C022",
        JOBTITLENAME: "담당",
        ORIGINALSTARTDATE: null,
        HIREDATE: "2021-04-29",
        STATUSBASIC: "재직",
        STATUSCURRENT: "재직",
        JOBCATEGORYCODE: "35010002",
        JOBCATEGORYNAME: "사무직",
        JOBTYPECODE: "35020003",
        JOBTYPENAME: "Production",
        JOBSERIALCODE: "35030010",
        JOBSERIALNAME: "품질",
        JOBCODE: "35170025",
        JOBNAME: "품질",
        JOBPOSITIONCODE: "A003",
        JOBPOSITIONNAME: "-",
        EMPLOYMENTTYPECODE: "D1",
        EMPLOYMENTTYPENAME: "사무직(연봉)",
        TEMPLATEIDS: "619",
        FORMDATAID: "3106",
        GROUPORGCODE: "SL01",
        GROUPORGNAME: "삼립그룹 조직",
        GROUPINSACODE: "SLINSA01",
        GROUPINSANAME: "삼립인사그룹",
        EVAL1ORGCODE: "33000065",
        EVAL1ORGNAME: "CSM팀",
        RATER1EMPNO: "20600010",
        RATER1NAME: "김용건",
        EVAL2ORGCODE: "33000854",
        EVAL2ORGNAME: "연구소",
        RATER2EMPNO: "1960004",
        RATER2NAME: "김진억",
        EVAL3ORGCODE: null,
        EVAL3ORGNAME: null,
        RATER3EMPNO: null,
        RATER3NAME: null,
        EVAL4ORGCODE: null,
        EVAL4ORGNAME: null,
        RATER4EMPNO: null,
        RATER4NAME: null,
        DELETEYN: null,
        SELFSCORE: null,
        EVALSCORE: "75.00",
        UPORGAVG: "68.67",
        UPORGSTDEV: "4.62",
        ORGAVG: "67.75",
        ORGSTDEV: "4.36",
        ADJUSTSCORE: "76.35",
        RANKING: 1,
        EVAL1GRADECODE: "001",
        EVAL1GRADENAME: "U",
        EVAL2SCORE: "76.36",
        EVAL2GRADECODE: "001",
        EVAL2GRADENAME: "U",
        EVAL3SCORE: null,
        EVAL3GRADECODE: null,
        EVAL3GRADENAME: null,
        EVAL4SCORE: null,
        EVAL4GRADECODE: null,
        EVAL4GRADENAME: null,
        FINALSCORE: null,
        FINALGRADECODE: null,
        FINALGRADENAME: null,
        STATUS: "99",
        COMFIRMEVAL: "N",
    },
    {
        CREATEDAT: "2024-07-22T01:01:23.342",
        CREATEDBY: "anonymous",
        MODIFIEDAT: "2024-07-22T04:39:38.084",
        MODIFIEDBY: "anonymous",
        EVALCODE: "SecondHalf2024",
        EMPNO: "38102378",
        NAME: "김재우",
        DEPARTMENTCODE: "33000457",
        DEPARTMENTNAME: "품질기획팀",
        ORGLEVEL2CODE: null,
        ORGLEVEL2NAME: null,
        ORGLEVEL3CODE: null,
        ORGLEVEL3NAME: null,
        ORGLEVEL4CODE: null,
        ORGLEVEL4NAME: null,
        ORGLEVEL5CODE: "33000502",
        ORGLEVEL5NAME: "품질경영실",
        ORGLEVEL6CODE: null,
        ORGLEVEL6NAME: null,
        ORGLEVEL7CODE: "33000457",
        ORGLEVEL7NAME: "품질기획팀",
        JOBGRADECODE: "35010002",
        JOBGRADENAME: "사무직",
        JOBTITLECODE: "C022",
        JOBTITLENAME: "담당",
        ORIGINALSTARTDATE: null,
        HIREDATE: "2021-04-29",
        STATUSBASIC: "재직",
        STATUSCURRENT: "재직",
        JOBCATEGORYCODE: "35010002",
        JOBCATEGORYNAME: "사무직",
        JOBTYPECODE: "35020003",
        JOBTYPENAME: "Production",
        JOBSERIALCODE: "35030010",
        JOBSERIALNAME: "품질",
        JOBCODE: "35170025",
        JOBNAME: "품질",
        JOBPOSITIONCODE: "A003",
        JOBPOSITIONNAME: "-",
        EMPLOYMENTTYPECODE: "D1",
        EMPLOYMENTTYPENAME: "사무직(연봉)",
        TEMPLATEIDS: "619",
        FORMDATAID: "3106",
        GROUPORGCODE: "SL01",
        GROUPORGNAME: "삼립그룹 조직",
        GROUPINSACODE: "SLINSA01",
        GROUPINSANAME: "삼립인사그룹",
        EVAL1ORGCODE: "33000065",
        EVAL1ORGNAME: "CSM팀",
        RATER1EMPNO: "20600010",
        RATER1NAME: "김용건",
        EVAL2ORGCODE: "33000854",
        EVAL2ORGNAME: "연구소",
        RATER2EMPNO: "1960004",
        RATER2NAME: "김진억",
        EVAL3ORGCODE: null,
        EVAL3ORGNAME: null,
        RATER3EMPNO: null,
        RATER3NAME: null,
        EVAL4ORGCODE: null,
        EVAL4ORGNAME: null,
        RATER4EMPNO: null,
        RATER4NAME: null,
        DELETEYN: null,
        SELFSCORE: null,
        EVALSCORE: "75.00",
        UPORGAVG: "68.67",
        UPORGSTDEV: "4.62",
        ORGAVG: "67.75",
        ORGSTDEV: "4.36",
        ADJUSTSCORE: "76.35",
        RANKING: 1,
        EVAL1GRADECODE: "001",
        EVAL1GRADENAME: "U",
        EVAL2SCORE: "76.36",
        EVAL2GRADECODE: "001",
        EVAL2GRADENAME: "U",
        EVAL3SCORE: null,
        EVAL3GRADECODE: null,
        EVAL3GRADENAME: null,
        EVAL4SCORE: null,
        EVAL4GRADECODE: null,
        EVAL4GRADENAME: null,
        FINALSCORE: null,
        FINALGRADECODE: null,
        FINALGRADENAME: null,
        STATUS: "12",
        COMFIRMEVAL: "N",
    }
];

// console.log(list);/**/
const mergedList = [];

const empMap = new Map();

list.forEach(item => {
    if (!empMap.has(item.EMPNO)) {
        empMap.set(item.EMPNO, {
            ...item,
            EVALCODES: [item.EVALCODE],
            EVALSCORES: [item.EVALSCORE],
            ADJUSTSCORES: [item.ADJUSTSCORE],
            STATUSES: [item.STATUS]
        });
    } else {
        const existingItem = empMap.get(item.EMPNO);
        existingItem.EVALCODES.push(item.EVALCODE);
        existingItem.EVALSCORES.push(item.EVALSCORE);
        existingItem.ADJUSTSCORES.push(item.ADJUSTSCORE);
        existingItem.STATUSES.push(item.STATUS);
    }
});

empMap.forEach(value => mergedList.push(value));

console.log(mergedList);
