let data = [
    {
        "evalYear": "2024",
        "evalCode": "spc",
        "companyCode": "8000",
        "companyName": "비알코리아㈜",
        "rater1Empno": "99999905",
        "rater1Name": "정팀장",
        "eval1OrgCode": "99999005",
        "eval1OrgName": "총무팀_TEST",
        "rater2Empno": "99999902",
        "rater2Name": "이실장",
        "eval2OrgCode": "99999002",
        "eval2OrgName": "인사실_TEST",
        "finalGradeCode": null,
        "finalGradeName": null,
        "pepoleCount": 0,
        "subDepartmentCount": 0,
        "avg": 0,
        "sd": 0,
        "adjustAvg": 0,
        "adjustSd": 0
    },
    {
        "evalYear": "2024",
        "evalCode": "spc",
        "companyCode": "8000",
        "companyName": "비알코리아㈜",
        "rater1Empno": "99999901",
        "rater1Name": "김총괄",
        "eval1OrgCode": "99999001",
        "eval1OrgName": "인사회계총괄_TEST",
        "rater2Empno": "PMGMADMIN",
        "rater2Name": "TM Test",
        "eval2OrgCode": null,
        "eval2OrgName": null,
        "finalGradeCode": null,
        "finalGradeName": null,
        "pepoleCount": 0,
        "subDepartmentCount": 0,
        "avg": 0,
        "sd": 0,
        "adjustAvg": 0,
        "adjustSd": 0
    },
    {
        "evalYear": "2024",
        "evalCode": "spc",
        "companyCode": "8000",
        "companyName": "비알코리아㈜",
        "rater1Empno": "99999901",
        "rater1Name": "김총괄",
        "eval1OrgCode": "99999001",
        "eval1OrgName": "인사회계총괄_TEST",
        "rater2Empno": "PMGMADMIN",
        "rater2Name": "TM Test",
        "eval2OrgCode": null,
        "eval2OrgName": null,
        "finalGradeCode": null,
        "finalGradeName": null,
        "pepoleCount": 0,
        "subDepartmentCount": 0,
        "avg": 0,
        "sd": 0,
        "adjustAvg": 0,
        "adjustSd": 0
    },
    {
        "evalYear": "2024",
        "evalCode": "spc",
        "companyCode": "8000",
        "companyName": "비알코리아㈜",
        "rater1Empno": "99999904",
        "rater1Name": "최팀장",
        "eval1OrgCode": "99999004",
        "eval1OrgName": "인사팀_TEST",
        "rater2Empno": "99999902",
        "rater2Name": "이실장",
        "eval2OrgCode": "99999002",
        "eval2OrgName": "인사실_TEST",
        "finalGradeCode": null,
        "finalGradeName": null,
        "pepoleCount": 0,
        "subDepartmentCount": 0,
        "avg": 0,
        "sd": 0,
        "adjustAvg": 0,
        "adjustSd": 0
    },
    {
        "evalYear": "2024",
        "evalCode": "spc",
        "companyCode": "8000",
        "companyName": "비알코리아㈜",
        "rater1Empno": "99999904",
        "rater1Name": "최팀장",
        "eval1OrgCode": "99999004",
        "eval1OrgName": "인사팀_TEST",
        "rater2Empno": "99999902",
        "rater2Name": "이실장",
        "eval2OrgCode": "99999002",
        "eval2OrgName": "인사실_TEST",
        "finalGradeCode": null,
        "finalGradeName": null,
        "pepoleCount": 0,
        "subDepartmentCount": 0,
        "avg": 0,
        "sd": 0,
        "adjustAvg": 0,
        "adjustSd": 0
    },
    {
        "evalYear": "2024",
        "evalCode": "spc",
        "companyCode": "8000",
        "companyName": "비알코리아㈜",
        "rater1Empno": "PMGMADMIN",
        "rater1Name": "TM Test",
        "eval1OrgCode": null,
        "eval1OrgName": null,
        "rater2Empno": null,
        "rater2Name": null,
        "eval2OrgCode": null,
        "eval2OrgName": null,
        "finalGradeCode": null,
        "finalGradeName": null,
        "pepoleCount": 0,
        "subDepartmentCount": 0,
        "avg": 0,
        "sd": 0,
        "adjustAvg": 0,
        "adjustSd": 0
    },
    {
        "evalYear": "2024",
        "evalCode": "spc",
        "companyCode": "8000",
        "companyName": "비알코리아㈜",
        "rater1Empno": "99999906",
        "rater1Name": "강팀장",
        "eval1OrgCode": "99999006",
        "eval1OrgName": "회계팀_TEST",
        "rater2Empno": "99999903",
        "rater2Name": "박실장",
        "eval2OrgCode": "99999003",
        "eval2OrgName": "회계실_TEST",
        "finalGradeCode": null,
        "finalGradeName": null,
        "pepoleCount": 0,
        "subDepartmentCount": 0,
        "avg": 0,
        "sd": 0,
        "adjustAvg": 0,
        "adjustSd": 0
    },
    {
        "evalYear": "2024",
        "evalCode": "spc",
        "companyCode": "8000",
        "companyName": "비알코리아㈜",
        "rater1Empno": "99999905",
        "rater1Name": "정팀장",
        "eval1OrgCode": "99999005",
        "eval1OrgName": "총무팀_TEST",
        "rater2Empno": "99999902",
        "rater2Name": "이실장",
        "eval2OrgCode": "99999002",
        "eval2OrgName": "인사실_TEST",
        "finalGradeCode": null,
        "finalGradeName": null,
        "pepoleCount": 0,
        "subDepartmentCount": 0,
        "avg": 0,
        "sd": 0,
        "adjustAvg": 0,
        "adjustSd": 0
    },
    {
        "evalYear": "2024",
        "evalCode": "spc",
        "companyCode": "8000",
        "companyName": "비알코리아㈜",
        "rater1Empno": "99999904",
        "rater1Name": "최팀장",
        "eval1OrgCode": "99999004",
        "eval1OrgName": "인사팀_TEST",
        "rater2Empno": "99999902",
        "rater2Name": "이실장",
        "eval2OrgCode": "99999002",
        "eval2OrgName": "인사실_TEST",
        "finalGradeCode": null,
        "finalGradeName": null,
        "pepoleCount": 0,
        "subDepartmentCount": 0,
        "avg": 0,
        "sd": 0,
        "adjustAvg": 0,
        "adjustSd": 0
    },
    {
        "evalYear": "2024",
        "evalCode": "spc",
        "companyCode": "8000",
        "companyName": "비알코리아㈜",
        "rater1Empno": "99999903",
        "rater1Name": "박실장",
        "eval1OrgCode": "99999003",
        "eval1OrgName": "회계실_TEST",
        "rater2Empno": "99999901",
        "rater2Name": "김총괄",
        "eval2OrgCode": "99999001",
        "eval2OrgName": "인사회계총괄_TEST",
        "finalGradeCode": null,
        "finalGradeName": null,
        "pepoleCount": 0,
        "subDepartmentCount": 0,
        "avg": 0,
        "sd": 0,
        "adjustAvg": 0,
        "adjustSd": 0
    },
    {
        "evalYear": "2024",
        "evalCode": "spc",
        "companyCode": "8000",
        "companyName": "비알코리아㈜",
        "rater1Empno": "99999902",
        "rater1Name": "이실장",
        "eval1OrgCode": "99999002",
        "eval1OrgName": "인사실_TEST",
        "rater2Empno": "99999901",
        "rater2Name": "김총괄",
        "eval2OrgCode": "99999001",
        "eval2OrgName": "인사회계총괄_TEST",
        "finalGradeCode": null,
        "finalGradeName": null,
        "pepoleCount": 0,
        "subDepartmentCount": 0,
        "avg": 0,
        "sd": 0,
        "adjustAvg": 0,
        "adjustSd": 0
    },
    {
        "evalYear": "2024",
        "evalCode": "spc",
        "companyCode": "8000",
        "companyName": "비알코리아㈜",
        "rater1Empno": "99999902",
        "rater1Name": "이실장",
        "eval1OrgCode": "99999002",
        "eval1OrgName": "인사실_TEST",
        "rater2Empno": "99999901",
        "rater2Name": "김총괄",
        "eval2OrgCode": "99999001",
        "eval2OrgName": "인사회계총괄_TEST",
        "finalGradeCode": null,
        "finalGradeName": null,
        "pepoleCount": 0,
        "subDepartmentCount": 0,
        "avg": 0,
        "sd": 0,
        "adjustAvg": 0,
        "adjustSd": 0
    },
    {
        "evalYear": "2024",
        "evalCode": "spc",
        "companyCode": "8000",
        "companyName": "비알코리아㈜",
        "rater1Empno": "99999905",
        "rater1Name": "정팀장",
        "eval1OrgCode": "99999005",
        "eval1OrgName": "총무팀_TEST",
        "rater2Empno": "99999902",
        "rater2Name": "이실장",
        "eval2OrgCode": "99999002",
        "eval2OrgName": "인사실_TEST",
        "finalGradeCode": null,
        "finalGradeName": null,
        "pepoleCount": 0,
        "subDepartmentCount": 0,
        "avg": 0,
        "sd": 0,
        "adjustAvg": 0,
        "adjustSd": 0
    }
];

let groupedData = data.reduce((acc, item) => {
    let key = `${item.evalYear}-${item.evalCode}-${item.companyCode}-${item.companyName}-${item.rater2Empno}-${item.rater2Name}`;

    if (!acc[key]) {
        acc[key] = {
            evalYear: item.evalYear,
            evalCode: item.evalCode,
            companyCode: item.companyCode,
            companyName: item.companyName,
            rater2Empno: item.rater2Empno,
            rater2Name: item.rater2Name,
            finalGradeCode: item.finalGradeCode,
            finalGradeName: item.finalGradeName,
            peopleCount: 0,
            subDepartmentCount: item.subDepartmentCount,
            avg: item.avg,
            sd: item.sd,
            adjustAvg: item.adjustAvg,
            adjustSd: item.adjustSd,
            detail1: []
        };
    }

    let subKey = `${item.rater1Empno}-${item.rater1Name}-${item.eval1OrgCode}-${item.eval1OrgName}`;
    let subDetail = acc[key].detail1.find(detail => `${detail.rater1Empno}-${detail.rater1Name}-${detail.eval1OrgCode}-${detail.eval1OrgName}` === subKey);

    if (!subDetail) {
        subDetail = {
            rater1Empno: item.rater1Empno,
            rater1Name: item.rater1Name,
            eval1OrgCode: item.eval1OrgCode,
            eval1OrgName: item.eval1OrgName,
            detail2: []
        };
        acc[key].detail1.push(subDetail);
    }

    subDetail.detail2.push({
        empno: item.rater1Empno,
        name: item.rater1Name,
        departmentCode: item.eval1OrgCode,
        departmentName: item.eval1OrgName
    });

    acc[key].peopleCount += 1;

    return acc;
}, {});

let result = Object.values(groupedData);

console.log(result);