let evalViewList = [
    {
        "evalYear": "2024",
        "evalCode": "spc",
        "companyCode": "8000",
        "companyName": "비알코리아㈜",
        "empno": "85112204",
        "name": "이상혁",
        "departmentCode": "99999005",
        "departmentName": "총무팀_TEST",
        "rater1Empno": "99999905",
        "rater1Name": "정팀장",
        "eval1OrgCode": "99999005",
        "eval1OrgName": "총무팀_TEST",
        "rater2Empno": "99999902",
        "rater2Name": "이실장",
        "eval2OrgCode": "99999002",
        "eval2OrgName": "인사실_TEST",
        "finalGradeCode": null,
        "finalGradeName": null,
        "pepoleCount": 0,
        "subDepartmentCount": 0,
        "avg": 0,
        "sd": 0,
        "adjustAvg": 0,
        "adjustSd": 0
    },
    {
        "evalYear": "2024",
        "evalCode": "spc",
        "companyCode": "8000",
        "companyName": "비알코리아㈜",
        "empno": "99999902",
        "name": "이실장",
        "departmentCode": "99999002",
        "departmentName": "인사실_TEST",
        "rater1Empno": "99999901",
        "rater1Name": "김총괄",
        "eval1OrgCode": "99999001",
        "eval1OrgName": "인사회계총괄_TEST",
        "rater2Empno": "PMGMADMIN",
        "rater2Name": "TM Test",
        "eval2OrgCode": null,
        "eval2OrgName": null,
        "finalGradeCode": null,
        "finalGradeName": null,
        "pepoleCount": 0,
        "subDepartmentCount": 0,
        "avg": 0,
        "sd": 0,
        "adjustAvg": 0,
        "adjustSd": 0
    },
    {
        "evalYear": "2024",
        "evalCode": "spc",
        "companyCode": "8000",
        "companyName": "비알코리아㈜",
        "empno": "99999903",
        "name": "박실장",
        "departmentCode": "99999003",
        "departmentName": "회계실_TEST",
        "rater1Empno": "99999901",
        "rater1Name": "김총괄",
        "eval1OrgCode": "99999001",
        "eval1OrgName": "인사회계총괄_TEST",
        "rater2Empno": "PMGMADMIN",
        "rater2Name": "TM Test",
        "eval2OrgCode": null,
        "eval2OrgName": null,
        "finalGradeCode": null,
        "finalGradeName": null,
        "pepoleCount": 0,
        "subDepartmentCount": 0,
        "avg": 0,
        "sd": 0,
        "adjustAvg": 0,
        "adjustSd": 0
    },
    {
        "evalYear": "2024",
        "evalCode": "spc",
        "companyCode": "8000",
        "companyName": "비알코리아㈜",
        "empno": "85112202",
        "name": "박재민",
        "departmentCode": "99999004",
        "departmentName": "인사팀_TEST",
        "rater1Empno": "99999904",
        "rater1Name": "최팀장",
        "eval1OrgCode": "99999004",
        "eval1OrgName": "인사팀_TEST",
        "rater2Empno": "99999902",
        "rater2Name": "이실장",
        "eval2OrgCode": "99999002",
        "eval2OrgName": "인사실_TEST",
        "finalGradeCode": null,
        "finalGradeName": null,
        "pepoleCount": 0,
        "subDepartmentCount": 0,
        "avg": 0,
        "sd": 0,
        "adjustAvg": 0,
        "adjustSd": 0
    },
    {
        "evalYear": "2024",
        "evalCode": "spc",
        "companyCode": "8000",
        "companyName": "비알코리아㈜",
        "empno": "85112203",
        "name": "임미쭤이",
        "departmentCode": "99999004",
        "departmentName": "인사팀_TEST",
        "rater1Empno": "99999904",
        "rater1Name": "최팀장",
        "eval1OrgCode": "99999004",
        "eval1OrgName": "인사팀_TEST",
        "rater2Empno": "99999902",
        "rater2Name": "이실장",
        "eval2OrgCode": "99999002",
        "eval2OrgName": "인사실_TEST",
        "finalGradeCode": null,
        "finalGradeName": null,
        "pepoleCount": 0,
        "subDepartmentCount": 0,
        "avg": 0,
        "sd": 0,
        "adjustAvg": 0,
        "adjustSd": 0
    },
    {
        "evalYear": "2024",
        "evalCode": "spc",
        "companyCode": "8000",
        "companyName": "비알코리아㈜",
        "empno": "99999901",
        "name": "김총괄",
        "departmentCode": "99999001",
        "departmentName": "인사회계총괄_TEST",
        "rater1Empno": "PMGMADMIN",
        "rater1Name": "TM Test",
        "eval1OrgCode": null,
        "eval1OrgName": null,
        "rater2Empno": null,
        "rater2Name": null,
        "eval2OrgCode": null,
        "eval2OrgName": null,
        "finalGradeCode": null,
        "finalGradeName": null,
        "pepoleCount": 0,
        "subDepartmentCount": 0,
        "avg": 0,
        "sd": 0,
        "adjustAvg": 0,
        "adjustSd": 0
    },
    {
        "evalYear": "2024",
        "evalCode": "spc",
        "companyCode": "8000",
        "companyName": "비알코리아㈜",
        "empno": "99999909",
        "name": "임팀원",
        "departmentCode": "99999006",
        "departmentName": "회계팀_TEST",
        "rater1Empno": "99999906",
        "rater1Name": "강팀장",
        "eval1OrgCode": "99999006",
        "eval1OrgName": "회계팀_TEST",
        "rater2Empno": "99999903",
        "rater2Name": "박실장",
        "eval2OrgCode": "99999003",
        "eval2OrgName": "회계실_TEST",
        "finalGradeCode": null,
        "finalGradeName": null,
        "pepoleCount": 0,
        "subDepartmentCount": 0,
        "avg": 0,
        "sd": 0,
        "adjustAvg": 0,
        "adjustSd": 0
    },
    {
        "evalYear": "2024",
        "evalCode": "spc",
        "companyCode": "8000",
        "companyName": "비알코리아㈜",
        "empno": "99999908",
        "name": "윤팀원",
        "departmentCode": "99999005",
        "departmentName": "총무팀_TEST",
        "rater1Empno": "99999905",
        "rater1Name": "정팀장",
        "eval1OrgCode": "99999005",
        "eval1OrgName": "총무팀_TEST",
        "rater2Empno": "99999902",
        "rater2Name": "이실장",
        "eval2OrgCode": "99999002",
        "eval2OrgName": "인사실_TEST",
        "finalGradeCode": null,
        "finalGradeName": null,
        "pepoleCount": 0,
        "subDepartmentCount": 0,
        "avg": 0,
        "sd": 0,
        "adjustAvg": 0,
        "adjustSd": 0
    },
    {
        "evalYear": "2024",
        "evalCode": "spc",
        "companyCode": "8000",
        "companyName": "비알코리아㈜",
        "empno": "99999907",
        "name": "손팀원",
        "departmentCode": "99999004",
        "departmentName": "인사팀_TEST",
        "rater1Empno": "99999904",
        "rater1Name": "최팀장",
        "eval1OrgCode": "99999004",
        "eval1OrgName": "인사팀_TEST",
        "rater2Empno": "99999902",
        "rater2Name": "이실장",
        "eval2OrgCode": "99999002",
        "eval2OrgName": "인사실_TEST",
        "finalGradeCode": null,
        "finalGradeName": null,
        "pepoleCount": 0,
        "subDepartmentCount": 0,
        "avg": 0,
        "sd": 0,
        "adjustAvg": 0,
        "adjustSd": 0
    },
    {
        "evalYear": "2024",
        "evalCode": "spc",
        "companyCode": "8000",
        "companyName": "비알코리아㈜",
        "empno": "99999906",
        "name": "강팀장",
        "departmentCode": "99999006",
        "departmentName": "회계팀_TEST",
        "rater1Empno": "99999903",
        "rater1Name": "박실장",
        "eval1OrgCode": "99999003",
        "eval1OrgName": "회계실_TEST",
        "rater2Empno": "99999901",
        "rater2Name": "김총괄",
        "eval2OrgCode": "99999001",
        "eval2OrgName": "인사회계총괄_TEST",
        "finalGradeCode": null,
        "finalGradeName": null,
        "pepoleCount": 0,
        "subDepartmentCount": 0,
        "avg": 0,
        "sd": 0,
        "adjustAvg": 0,
        "adjustSd": 0
    },
    {
        "evalYear": "2024",
        "evalCode": "spc",
        "companyCode": "8000",
        "companyName": "비알코리아㈜",
        "empno": "99999905",
        "name": "정팀장",
        "departmentCode": "99999005",
        "departmentName": "총무팀_TEST",
        "rater1Empno": "99999902",
        "rater1Name": "이실장",
        "eval1OrgCode": "99999002",
        "eval1OrgName": "인사실_TEST",
        "rater2Empno": "99999901",
        "rater2Name": "김총괄",
        "eval2OrgCode": "99999001",
        "eval2OrgName": "인사회계총괄_TEST",
        "finalGradeCode": null,
        "finalGradeName": null,
        "pepoleCount": 0,
        "subDepartmentCount": 0,
        "avg": 0,
        "sd": 0,
        "adjustAvg": 0,
        "adjustSd": 0
    },
    {
        "evalYear": "2024",
        "evalCode": "spc",
        "companyCode": "8000",
        "companyName": "비알코리아㈜",
        "empno": "99999904",
        "name": "최팀장",
        "departmentCode": "99999004",
        "departmentName": "인사팀_TEST",
        "rater1Empno": "99999902",
        "rater1Name": "이실장",
        "eval1OrgCode": "99999002",
        "eval1OrgName": "인사실_TEST",
        "rater2Empno": "99999901",
        "rater2Name": "김총괄",
        "eval2OrgCode": "99999001",
        "eval2OrgName": "인사회계총괄_TEST",
        "finalGradeCode": null,
        "finalGradeName": null,
        "pepoleCount": 0,
        "subDepartmentCount": 0,
        "avg": 0,
        "sd": 0,
        "adjustAvg": 0,
        "adjustSd": 0
    },
    {
        "evalYear": "2024",
        "evalCode": "spc",
        "companyCode": "8000",
        "companyName": "비알코리아㈜",
        "empno": "85112205",
        "name": "신포도",
        "departmentCode": "99999005",
        "departmentName": "총무팀_TEST",
        "rater1Empno": "99999905",
        "rater1Name": "정팀장",
        "eval1OrgCode": "99999005",
        "eval1OrgName": "총무팀_TEST",
        "rater2Empno": "99999902",
        "rater2Name": "이실장",
        "eval2OrgCode": "99999002",
        "eval2OrgName": "인사실_TEST",
        "finalGradeCode": null,
        "finalGradeName": null,
        "pepoleCount": 0,
        "subDepartmentCount": 0,
        "avg": 0,
        "sd": 0,
        "adjustAvg": 0,
        "adjustSd": 0
    }
];

// 그룹화 함수
let groupedData = evalViewList.reduce((acc, item) => {
    // 최상위 그룹화 키 생성
    let key = `${item.evalYear}-${item.evalCode}-${item.companyCode}-${item.companyName}-${item.rater2Empno}-${item.rater2Name}-${item.eval2OrgCode}-${item.eval2OrgName}`;

    if (!acc[key]) {
        acc[key] = {
            evalYear: item.evalYear,
            evalCode: item.evalCode,
            companyCode: item.companyCode,
            companyName: item.companyName,
            rater2Empno: item.rater2Empno,
            rater2Name: item.rater2Name,
            eval2OrgCode: item.eval2OrgCode,
            eval2OrgName: item.eval2OrgName,
            detail1: []
        };
    }

    // detail1 그룹화 키 생성
    let subKey = `${item.rater1Empno}-${item.rater1Name}-${item.eval1OrgCode}-${item.eval1OrgName}`;
    let subDetail = acc[key].detail1.find(detail => `${detail.rater1Empno}-${detail.rater1Name}-${detail.eval1OrgCode}-${detail.eval1OrgName}` === subKey);

    if (!subDetail) {
        subDetail = {
            rater1Empno: item.rater1Empno,
            rater1Name: item.rater1Name,
            eval1OrgCode: item.eval1OrgCode,
            eval1OrgName: item.eval1OrgName,
            detail2: []
        };
        acc[key].detail1.push(subDetail);
    }

    // detail2 데이터 추가
    subDetail.detail2.push({
        empno: item.empno,
        name: item.name,
        departmentCode: item.departmentCode,
        departmentName: item.departmentName
    });

    return acc;
}, {});

// peopleCount와 subDepartmentCount 계산
for (let key in groupedData) {
    let group = groupedData[key];
    group.detail1.forEach(subDetail => {
        subDetail.peopleCount = subDetail.detail2.length;

        // subDepartmentCount 계산
        let departmentSet = new Set();
        subDetail.detail2.forEach(detail2 => {
            departmentSet.add(`${detail2.departmentCode}-${detail2.departmentName}`);
        });
        subDetail.subDepartmentCount = departmentSet.size;
    });
}

// 결과 배열 생성
let result = Object.values(groupedData);

console.log(result);