let list1 = [
    {
        "createdAt": "2024-06-27T01:52:42.525Z",
        "createdBy": "anonymous",
        "modifiedAt": "2024-06-27T01:52:42.525Z",
        "modifiedBy": "anonymous",
        "distributionCode": "dis1",
        "personCount": 3,
        "orgLevelCode": "01",
        "orgLevelName": "E",
        "gradeCode": "personGrade2",
        "gradeName": "개인평가등급",
        "levelCode1": "05",
        "levelCodeCount1": 1,
        "levelCode2": "04",
        "levelCodeCount2": 1,
        "levelCode3": "03",
        "levelCodeCount3": 1,
        "levelCode4": null,
        "levelCodeCount4": null,
        "levelCode5": null,
        "levelCodeCount5": null,
        "levelCode6": null,
        "levelCodeCount6": null,
        "levelCode7": null,
        "levelCodeCount7": null,
        "levelCode8": null,
        "levelCodeCount8": null,
        "budgetPoint": 6
    },
    {
        "createdAt": "2024-06-27T01:52:31.562Z",
        "createdBy": "anonymous",
        "modifiedAt": "2024-06-27T01:52:31.562Z",
        "modifiedBy": "anonymous",
        "distributionCode": "dis1",
        "personCount": 3,
        "orgLevelCode": "02",
        "orgLevelName": "G",
        "gradeCode": "personGrade2",
        "gradeName": "개인평가등급",
        "levelCode1": "05",
        "levelCodeCount1": 1,
        "levelCode2": "04",
        "levelCodeCount2": 1,
        "levelCode3": "03",
        "levelCodeCount3": 1,
        "levelCode4": null,
        "levelCodeCount4": null,
        "levelCode5": null,
        "levelCodeCount5": null,
        "levelCode6": null,
        "levelCodeCount6": null,
        "levelCode7": null,
        "levelCodeCount7": null,
        "levelCode8": null,
        "levelCodeCount8": null,
        "budgetPoint": 6
    },
    {
        "createdAt": "2024-06-27T01:52:17.327Z",
        "createdBy": "anonymous",
        "modifiedAt": "2024-06-27T01:52:17.327Z",
        "modifiedBy": "anonymous",
        "distributionCode": "dis1",
        "personCount": 3,
        "orgLevelCode": "03",
        "orgLevelName": "M",
        "gradeCode": "personGrade2",
        "gradeName": "개인평가등급",
        "levelCode1": "05",
        "levelCodeCount1": 1,
        "levelCode2": "04",
        "levelCodeCount2": 1,
        "levelCode3": "03",
        "levelCodeCount3": 1,
        "levelCode4": null,
        "levelCodeCount4": null,
        "levelCode5": null,
        "levelCodeCount5": null,
        "levelCode6": null,
        "levelCodeCount6": null,
        "levelCode7": null,
        "levelCodeCount7": null,
        "levelCode8": null,
        "levelCodeCount8": null,
        "budgetPoint": 6
    },
    {
        "createdAt": "2024-06-27T01:52:08.644Z",
        "createdBy": "anonymous",
        "modifiedAt": "2024-06-27T01:52:08.644Z",
        "modifiedBy": "anonymous",
        "distributionCode": "dis1",
        "personCount": 3,
        "orgLevelCode": "04",
        "orgLevelName": "I",
        "gradeCode": "personGrade2",
        "gradeName": "개인평가등급",
        "levelCode1": "05",
        "levelCodeCount1": 1,
        "levelCode2": "04",
        "levelCodeCount2": 1,
        "levelCode3": "03",
        "levelCodeCount3": 1,
        "levelCode4": null,
        "levelCodeCount4": null,
        "levelCode5": null,
        "levelCodeCount5": null,
        "levelCode6": null,
        "levelCodeCount6": null,
        "levelCode7": null,
        "levelCodeCount7": null,
        "levelCode8": null,
        "levelCodeCount8": null,
        "budgetPoint": 6
    },
    {
        "createdAt": "2024-06-27T01:52:08.644Z",
        "createdBy": "anonymous",
        "modifiedAt": "2024-06-27T01:52:08.644Z",
        "modifiedBy": "anonymous",
        "distributionCode": "dis1",
        "personCount": 3,
        "orgLevelCode": "05",
        "orgLevelName": "U",
        "gradeCode": "personGrade2",
        "gradeName": "개인평가등급",
        "levelCode1": "05",
        "levelCodeCount1": 1,
        "levelCode2": "04",
        "levelCodeCount2": 1,
        "levelCode3": "03",
        "levelCodeCount3": 1,
        "levelCode4": null,
        "levelCodeCount4": null,
        "levelCode5": null,
        "levelCodeCount5": null,
        "levelCode6": null,
        "levelCodeCount6": null,
        "levelCode7": null,
        "levelCodeCount7": null,
        "levelCode8": null,
        "levelCodeCount8": null,
        "budgetPoint": 6
    }
]

console.log(list1);

let newList = new Set();
let perList = list1.map((o=> o.personCount));
let uniqueSet = new Set(perList);
console.log(Array.from(uniqueSet));
