let value = [
    {
        userId: "0210539",
        grade: "3020",
        gradeName: "V2급",
        degreeCode: "80",
        degreeName: "고졸",
        year6ago: 0,
        year5ago: 0,
        year4ago: 0,
        year3ago: 0,
        year2ago: 0,
        year1ago: 100,
        count: 1,
        promotionPeriod: 3,
    },
    {
        userId: "0410514",
        grade: "3020",
        gradeName: "V2급",
        degreeCode: "80",
        degreeName: "고졸",
        year6ago: 0,
        year5ago: 0,
        year4ago: 0,
        year3ago: 0,
        year2ago: 0,
        year1ago: 75,
        count: 1,
        promotionPeriod: 3,
    },
    {
        userId: "0510817",
        grade: "3020",
        gradeName: "V2급",
        degreeCode: "80",
        degreeName: "고졸",
        year6ago: 0,
        year5ago: 0,
        year4ago: 0,
        year3ago: 0,
        year2ago: 0,
        year1ago: 95,
        count: 1,
        promotionPeriod: 3,
    },
]

console.log(value);